import {
  createIssue,
  mapCategoryToLabel,
  mapPriorityToLinear,
} from "../services/linear-service.js";

const NEW_STATE_ID = "e7a9d144-5d41-4fe5-a96b-28d05810d774";

/**
 * Builds a Linear issue from the triage result and creates it.
 *
 * @param {object} ticket
 * @param {string} ticket.id
 * @param {string} ticket.sender
 * @param {string} ticket.message
 * @param {string} ticket.slackChannel
 * @param {string} ticket.slackMessageTs
 * @param {object} triageResult
 * @param {string} triageResult.category
 * @param {string} triageResult.priority
 * @param {string} triageResult.summary
 * @param {string} triageResult.subject
 * @param {string} triageResult.actionPlan
 * @returns {Promise<{id: string, url: string, identifier: string}>}
 */
export async function planAndCreateIssue(ticket, triageResult) {
  const title = `[${ticket.id}] ${triageResult.subject}`;

  const description = [
    `## Support Ticket`,
    `- **Ticket ID:** ${ticket.id}`,
    `- **Category:** ${triageResult.category}`,
    `- **Priority:** ${triageResult.priority}`,
    `- **Reported by:** ${ticket.sender}`,
    `- **Channel:** ${ticket.slackChannel}`,
    ``,
    `## Original Message`,
    `> ${ticket.message}`,
    ``,
    `## Summary`,
    triageResult.summary,
    ``,
    `## Action Plan`,
    triageResult.actionPlan,
    ``,
    `---`,
    `_Auto-generated by Automated Support system_`,
  ].join("\n");

  const labelId = mapCategoryToLabel(triageResult.category);
  const labelIds = labelId ? [labelId] : [];
  const priority = mapPriorityToLinear(triageResult.priority);

  const issue = await createIssue({
    title,
    description,
    priority,
    labelIds,
    stateId: NEW_STATE_ID,
  });

  return {
    id: issue.id,
    url: issue.url,
    identifier: issue.identifier,
  };
}
